#!/bin/bash

if [[ ! -d 'script' ]]; then
    echo "Must be in top level of repo"
    exit 1
fi

pushd terraform-files
terraform destroy || echo "Terraform operation failed. See output for details."
popd
